### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by groz** [groz/play-shooter#1]
- [x] Add common needed functionality to scala Vector2 (scale, rotate, add, length, etc)
- [x] Add walls objects to server side
- [x] Calc visible enemies on the server taking walls into account
- [ ] Setup deployment to AWS (Tagir)
- [ ] Visualize walls and players on client-side (Tagir)
- [ ] Run game loop on server/client (Tagir)
- [ ] Add tests for calc visible enemies
- [ ] Add kd-tree(?) to disable large chunks for detection
